# Generated by Django 5.1.2 on 2024-11-27 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='direcciones_envio',
            name='Usuarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='Usuarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='direcciones_envio',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='direcciones_envio',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='ordenes',
            name='total',
        ),
        migrations.AddField(
            model_name='carritodecompras',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='direcciones_envio',
            name='Canton',
            field=models.CharField(default='Sin canton', max_length=100),
        ),
        migrations.AddField(
            model_name='direcciones_envio',
            name='Distrito',
            field=models.CharField(default='Sin distrito', max_length=100),
        ),
        migrations.AddField(
            model_name='direcciones_envio',
            name='provincia',
            field=models.CharField(default='Sin provincia', max_length=255),
        ),
        migrations.AddField(
            model_name='productos',
            name='imagen_product',
            field=models.BinaryField(default=0),
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
