# Generated by Django 5.1.2 on 2024-11-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_direcciones_envio_usuarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen_product',
            field=models.TextField(default='0'),
        ),
    ]
