# Generated by Django 5.1.2 on 2024-12-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_carritodecompras_productos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='comprobante_pago',
            field=models.TextField(default='0'),
        ),
    ]
